services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: movie-search-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker/mongo-data:/data/db
    user: "999:999"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
